export enum SolicitationStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  CHANGE_REQUESTED = 'CHANGE_REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  TERMINATED_APPROVED = 'TERMINATED_APPROVED',
  TERMINATED_REJECTED = 'TERMINATED_REJECTED',
}
